# Generated by Django 3.0.3 on 2020-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broduct',
            name='category',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
